const words = [
  { word: "abacaxi", clue: "Fruta tropical" },
  { word: "elefante", clue: "Animal de grande porte com tromba longa" },
  { word: "computador", clue: "Dispositivo eletrônico" },
  { word: "girafa", clue: "Animal alto, com pescoço longo" },
  { word: "chocolate", clue: "Doce feito de cacau" },
  { word: "piano", clue: "Instrumento musical com teclas" },
  { word: "tigre", clue: "Felino selvagem" },
  { word: "esmeralda", clue: "Tipo de pedra preciosa" },
  { word: "navio", clue: "Embarcação no mar" },
  { word: "telefone", clue: "Dispositivo de comunicação" },
  { word: "floresta", clue: "Área com muitas árvores" },
  { word: "quadrado", clue: "Figura geométrica de quatro lados" },
  { word: "foguete", clue: "Veículo espacial" },
  { word: "sorvete", clue: "Doce gelado" },
  { word: "bicicleta", clue: "Veículo de duas rodas" },
  { word: "avião", clue: "Meio de transporte aéreo" },
  { word: "macaco", clue: "Primate arbóreo" },
  { word: "raios", clue: "Descargas elétricas na atmosfera" },
  { word: "montanha", clue: "Elevação natural da terra" },
  { word: "vela", clue: "Objeto para iluminação" },
  { word: "mochila", clue: "Usada para carregar materiais escolares" },
  { word: "planeta", clue: "Corpo celeste que orbita uma estrela" },
  { word: "tartaruga", clue: "Animal com casco" },
  { word: "oceano", clue: "Grande massa de água salgada" },
  { word: "jardim", clue: "Lugar com plantas e flores" },
  { word: "borboleta", clue: "Inseto com asas coloridas" },
  { word: "lápis", clue: "Usado para escrever ou desenhar" },
  { word: "castelo", clue: "Fortaleza medieval" },
  { word: "ferradura", clue: "Proteção para cascos de cavalos" },
  { word: "escada", clue: "Usada para subir ou descer" },
  { word: "canoa", clue: "Barco pequeno" },
  { word: "relógio", clue: "Marca as horas" },
  { word: "montanha", clue: "Elevação natural da terra" },
  { word: "bússola", clue: "Instrumento que aponta para o norte" },
  { word: "arcoiris", clue: "Fenômeno óptico colorido no céu" },
  { word: "cachoeira", clue: "Queda d'água" },
  { word: "coelho", clue: "Animal conhecido por suas orelhas longas" },
  { word: "livro", clue: "Conjunto de páginas com histórias ou informações" },
  { word: "microfone", clue: "Usado para amplificar a voz" },
  { word: "televisão", clue: "Dispositivo para assistir programas" },
  { word: "prateleira", clue: "Estrutura para guardar livros ou objetos" },
  { word: "guitarra", clue: "Instrumento musical de cordas" },
  { word: "espelho", clue: "Reflete a imagem" },
  { word: "diamante", clue: "Joia preciosa" },
  { word: "ônibus", clue: "Meio de transporte coletivo" },
  { word: "cavalo", clue: "Animal usado para montaria" }
];

  
  export default function getWord() {
    const index = Math.floor(Math.random() * words.length);
    return words[index];
  }